App\Domain\Entity\Video:

    properties:
        id:
            - Uuid:
                message: L'attribut id n'est pas un Uuid valide.
                groups:
                    - trick
        iFrame:
            - NotBlank:
                message: Nous avons besoin de l'iFrame.
                groups:
                    - trick