framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    validation:
        enabled: true

    session:
        handler_id: ~

    php_errors:
        log: true

sensio_framework_extra:
    router:
        annotations: false