framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    validation:
        enabled: true

#    assets:
#        base_urls: 'http://snowtricks.vincentlescot.fr/public/'

    session:
        handler_id: ~

    php_errors:
        log: true

sensio_framework_extra:
    router:
        annotations: false