parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $publicFolder: '%kernel.project_dir%/public'

    doctrine_migrations:
        resource: '%kernel.root_dir%/Domain/Migrations'
        namespace: 'App\Domain\Migrations\'
#    doctrine_migrations:
#        dir_name: '%kernel.project_dir%/src/Domain/Migrations'
#        namespace: 'DoctrineMigrations'

    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

    app.security.login_form_authenticator:
        class: App\UI\Security\LoginFormAuthenticator

    app.security.access_denied_handler:
        class: App\UI\Security\AccessDeniedHandler

    App\Service\Image\ImageUploadWarmer:
        arguments:
            $trickFolder: '/image/trick'
            $userFolder: '/image/user'

    App\Service\Image\ImageThumbnailCreator:
        arguments:
            $thumbnailsWidth: '400'
            $thumbnailsAltPrefix: 'thumbnail-'