parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $publicFolder: '%kernel.project_dir%/public'

    doctrine_migrations:
        resource: '%kernel.root_dir%/Domain/Migrations'
        namespace: 'App\Domain\Migrations\'

    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

#    SECURITY
    app.security.login_form_authenticator:
        class: App\UI\Security\LoginFormAuthenticator

    app.security.logout_success_handler:
        class: App\UI\Security\LogoutSuccessHandler

#    SERVICES
    App\Service\Image\ImageUploadWarmer:
        arguments:
            $trickFolder: '/image/snowtrick'
            $userFolder: '/image/user'

    App\Service\Image\ImageThumbnailCreator:
        arguments:
            $thumbnailsWidth: '400'
            $thumbnailsAltPrefix: 'thumbnail-'